server:
  port: 7071
spring:
  security:
    user:
      name: java10
      password: 123
  rabbitmq:
    host: localhost
    port: 5672
    username: socialmedia
    password: root
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/java10SocialAuth
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

rabbitmq:
  auth-exchange: auth-exchange
  register-binding-key: register-key
  register-queue: register-queue
  activation-binding-key: activation-key
  activation-queue: queue-activation
  mail-queue: queue-mail
  mail-binding-key: mail-key


