server:
  port: 7073
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: socialmedia
    password: root
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: JavaUser
      password: root
      database: socialmedia

redis:
  host: localhost
  port: 6379
