server:
  port: 7072
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java10
    password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/java10SocialUser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secretKey: ${java10secretkey}
  issuer: ${java10issuer}
rabbitmq:
  register-queue: register-queue